image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Install genezio
      before: npm install -g genezio@latest
      command: genezio --version
    - name: Friendly message
      command: echo "Run genezio deploy to try out this project"
