/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package geneziokotlin

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = HelloWorldService()
        assertNotNull(classUnderTest.methodWithVoidReturnVoidCount, "app should have a greeting")
    }
}
