/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package geneziotestclient
import sdk.*
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val kt = sdk.HelloWorldService()

    println(kt.helloWorld())
    println(kt.helloWorldWithParam("George"))
    println(kt.helloWorldWithObject(Person("George", 24)))
    println(kt.comparePersonAge(Person("George", 24), Person("John", 25)))

}
